### ISSUE TITLE
Put uri-bytestring back into stackage

### ISSUE THREAD

**Issue by sjakobi** [Soostone/uri-bytestring#30]
It would be nice to have uri-bytestring back in the stackage nightlies. Its dependencies all seem to be there!

**Comment by MichaelXavier** [comment]
I believe the issue is with test dependencies, specifically lens-simple and friends not being on stackage. I've chased it down a little bit and it seems like the dependencies can't resolve due to some overly strict bounds to [lens-simple](https://github.com/michaelt/lens-simple), but the version in the github repo has been updated with broader bounds, so I think that just needs a release. I'll try to see if I can submit a PR that gets lens-simple building on GHC-8, at which point it could get a release. In any case, I don't know that not being able to run tests on one resolver is reason to exclude the package entirely, so if that doesn't work out, the package should be reinstated. I'll ask the stackage people for guidance in that case.

**Comment by MichaelXavier** [comment]
Requested release of lens-simple [here](https://github.com/michaelt/lens-simple/issues/1)

**Comment by sjakobi** [comment]
Thanks for taking care of this!

**Comment by MichaelXavier** [comment]
Reinstatement requested here https://github.com/fpco/stackage/pull/1644

**Comment by MichaelXavier** [comment]
And we're back https://www.stackage.org/nightly-2016-06-27/package/uri-bytestring-0.2.1.2
