### ISSUE TITLE
expose Arbitrary instances

### ISSUE THREAD

**Issue by fisx** [Soostone/uri-bytestring#45]
I would like to generate URIs for my own property tests.  I see the following options:

- Export URI.ByteString.Arbitrary as a library module, and leave it to the library user not to import it, and to ghc to strip it out of production code (not sure that'll happen).
- Create a cabal flag for conditional exporting of that module (I *think* this should be feasible).
- Create one more package for the type, and one for the Arbitrary instances, and depend on the former in uri-bytestring-the-library, and the former and the second in the tests.  This is of course quite silly.

Would you accept a PR for the first option?  If not, for the second?

thanks!

**Comment by mightybyte** [comment]
Just a side note, if you don't want all the overhead of Arbitrary, there's a type class solely for the purpose of generating fake data in [fake](http://hackage.haskell.org/package/fake).

**Comment by fisx** [comment]
interesting, thanks!  (this time i just want to do quickcheck testing, though.)

**Comment by MichaelXavier** [comment]
In general these days I'm not a fan of using typeclasses for property testing and this is one of the reasons. I'm more apt to use hedgehog, which gives you per-test granularity for generating test cases rather than having to specify everything universally with Arbitrary, and avoiding the issue of conflicting or orphaned instances. I don't want to add QuickCheck as a dependency in the main library, nor add flags to dance around the issue.

I would be okay with option 3 where there's a separate QuickCheck instances library, as is often done. If you wanted to do that I'd drop out my arbitrary instances and depend on that package, I suppose. If I were going to to through that effort myself, I'd just as soon drop QuickCheck entirely and create a module of hedgehog generators.

If I were you though and I needed Arbitrary instances for URIs, I'd just copy the URI.ByteString.Arbitrary module into my project.

**Comment by fisx** [comment]
ok, i'll think about copying.  i'm beginning to like the idea.  (-:

just curious, though: i agree with your preference of hedgehog, but how does that solve the issue here?  it's not the type class that is causing the problem, but the situation where we want to export parts of the test suite to other packages so they can use them to write other tests.  how does hedgehog solve that?  you'd still depend on a test library in options 1, 2.

anyway.  great library.  thanks again.

**Comment by MichaelXavier** [comment]
You're absolutely right that hedgehog doesn't solve the problem completely. The problem, if I understand it correctly, is that users may want to generate arbitrary values for their own tests. They could vendor their own generators (be they quickcheck or hedgehog-based), but this is essentially boring, repetitive work that every such user would have to do redundantly. So, the only way to share that code is to either produce a separate library with the generators built in or export it as part of the main library itself, but unfortunately incur dependencies or CPP tricks in the process.

The only part that hedgehog improves on there is that if you were to export generators, users can pick and choose which to use and freely modify them because they're at the term level. If they were quickcheck instances, the publisher is restricting the users.

So I should say, I would accept a PR which turns this repo into a monorepo with `uri-bytestring-quickcheck` or `uri-bytestring-hedgehog` or something. I'd also happily use a library version of the arbitrary instances on your own repos (though keeping them in sync might get weird?). These are both a lot of work though so I completely understand why you may be disinclined to do it that way. That's why I'm not in any rush to do them :laughing:

**Comment by fisx** [comment]
(you're not coming to zurihac this week-end by any chance, are you?)

**Comment by MichaelXavier** [comment]
Not going to Zurihac, I don't leave the house :laughing:

Are you sure about needing the types module as a separate package? I know you can't have circular dependencies with modules but does that also apply to packages? URI.ByteString.Arbitrary could import URI.ByteString.Types and then the tests could import URI.ByteString.Arbitrary and there shouldn't be a circular *module* dependency.

**Comment by fisx** [comment]
the more i think about it, the more i think that CPP would be a perfectly nice solution.  there is already plenty of CPP in this package, and it would certainly be easier to maintain the one package rather than the three.

but of course i'm happy to let you make the call.

feel free to close this now if you're already bored with it.  (-:

**Comment by MichaelXavier** [comment]
Woof, that's an ordeal. I guess that will teach me to throw out half-baked suggestions. So how would the CPP work? If the flag is sent, you'd add `test` to the source tree, `quickcheck` to the dependencies and the arbitrary module to the exported modules list?

**Comment by fisx** [comment]
No, please don't stop making half-baked suggestions!  As long as you don't know they are doomed, it's always interesting.  :-)

> If the flag is sent, you'd add test to the source tree, quickcheck to the dependencies and the arbitrary module to the exported modules list?

I was thinking to keep the modules that go into the package under `src`, i.e. move `Arbitrary` and potentially `Hedgehog` to `URI.ByteString.Test.*`.  To run the test suite, you would have to compile the library with the flag set.

If you have any preference, I'll try that one out first.

(I'm slowing down with my responses, but I am still optimistic about following through with this, so please bear with me.)

**Comment by fisx** [comment]
Tried your idea in #48.  I'm quite happy with it, except for the questions I raised in the description.

Your turn.  Take your time, though.  :-)

**Comment by fisx** [comment]
Ok, I'm giving up.  Don't worry, I was just curious where this would take me.  Closing #48, #46, #45.

Thanks!

**Comment by MichaelXavier** [comment]
No problem. Cheers for trying!
